rova: patches: Fix double bind mounting /data/media on FDE devices
* this fixes double bind mounting of /data/media when decrypted on FDE
  devices, which previously made data formatting impossible, because the
  kernel was unable to remove device mapper block in /dev/block/dm-0.
* also it fixes Internal Storage visibility though MTP.

    E:Cannot remove dm-crypt device
    E:Error deleting crypto block device, continuing anyway.
    I:mkfs.f2fs command: /system/bin/make_f2fs -g android /dev/block/mmcblk0p49 2588151 && sload_f2fs -t /data /dev/block/mmcblk0p49

            F2FS-tools: mkfs.f2fs Ver: 1.13.0 (2019-09-24)

    Info: Disable heap-based policy
    Info: Debug level = 1
    Info: Trim is enabled
    Info: Set conf for android
            Error: In use by the system!
    /system/bin/make_f2fs -g android /dev/block/mmcblk0p49 2588151 && sload_f2fs -t /data /dev/block/mmcblk0p49 process ended with ERROR: 255
    Unable to wipe Data.
    Unable to format to remove encryption.

Signed-off-by: iusmac <iusico.maxim@libero.it>